db:
  image: postgres
web:
  build: .
  command: gunicorn {{app_name}}.wsgi:application -b :8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
qc:
  image: codeclimate/codeclimate
